name: Build release APK

on:
  push:
    tags:
      - "v*.*.*"
      - "!v*.*.*-fd"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      - name: Sign APK
        # ID used to access action output
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Rename APK
        run: mv ${{steps.sign_apk.outputs.signedReleaseFile}} release.apk
      - run: echo "Build status report=${{ job.status }}."
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: release.apk
          path: release.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repository: idunnololz/summit-for-lemmy
          token: ${{ secrets.GH_TOKEN }}
          files: release.apk
